import Head from "next/head";
import Image from "next/image";
import NavBarTop from "../../components/NavBarTop";
import Footer from "../../components/Footer";
import { FaRegCalendarAlt, FaMapMarkerAlt } from "react-icons/fa";

export default function Agendaetail({ agenda }) {
    // console.log(post.author)
    return (
        <>
            <style jsx>
                {`
                main {
                    margin-top: 60px;
                    min-height: 100vh;
                }
                .card-title {
                    font-weight: 500;
                }
                .shadow-blog {
                    box-shadow: 0 4px 16px rgb(0 0 0 / 10%);
                }
                .blog-meta a .icon {
                    font-size: 15px;
                    color: #495057;
                }
                .blog-meta a {
                    font-size: 14px;
                    text-decoration: none;
                    color: #495057;
                }
                .blog-meta a:hover {
                    color: #0d6efd;
                }
                .card-text {
                    color: #495057;
                    font-size: 16px;
                }
            `}
            </style>

            <Head>
                <title>{`${agenda.title} - Next Bootstrap`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <NavBarTop />

            <main>
                <div className="container py-5">
                    <div className="row g-4">
                        <div className="col-md-8">
                            <div className="card shadow-blog border-0">
                                <Image
                                    alt="Image"
                                    src={agenda.image}
                                    width="450"
                                    height="400"
                                    className="card-img-top img-fluid"
                                />
                                <div className="card-body">
                                    <h3 className="card-title">{agenda.title}</h3>
                                    <div className="d-block d-sm-flex blog-meta py-2">
                                        <div className="d-flex mb-2">
                                            <FaRegCalendarAlt />
                                            <small className="text-muted ms-2">{agenda.time} - {agenda.date}</small>
                                        </div>
                                        <div className="d-flex ms-0 ms-sm-3">
                                            <FaMapMarkerAlt />
                                            <small className="text-muted ms-2">{agenda.location}</small>
                                        </div>
                                    </div>
                                    <p className="card-text mt-2">{agenda.body}</p>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-4 px-4">
                            {/* <div className="card shadow-sm">
                                
                            </div> */}
                        </div>
                    </div>
                </div>
            </main>
            
            <Footer />
        </>
    );
};

// This gets called on every request to this page
export async function getServerSideProps({ params }) {
    // console.log(params.slug)
    // Call external API from here directly using slug params
    const getSingleAgenda = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/agenda/${params.slug}`);
    const agenda = await getSingleAgenda.json();
    // console.log(getSinglePost.status)
    // handle detail not found to 404 page
    if (getSingleAgenda.status == 404) {
        return {
            notFound: true,
        };
    } 
    return {
        props: { agenda },
    };
};