import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import NavBarTop from "../../components/NavBarTop";
import Footer from "../../components/Footer";
import { FaUser, FaRegCalendarAlt, FaArrowRight } from "react-icons/fa";

export default function BlogDetail({ post }) {
    // console.log(post.author)
    return (
        <>
            <style jsx>
                {`
                main {
                    margin-top: 60px;
                    min-height: 100vh;
                }
                .card-title {
                    font-weight: 500;
                }
                .shadow-blog {
                    box-shadow: 0 4px 16px rgb(0 0 0 / 10%);
                }
                .blog-meta a .icon {
                    font-size: 15px;
                    color: #495057;
                }
                .blog-meta a {
                    font-size: 14px;
                    text-decoration: none;
                    color: #495057;
                }
                .blog-meta a:hover {
                    color: #0d6efd;
                }
                .card-text {
                    color: #495057;
                    font-size: 16px;
                }
            `}
            </style>

            <Head>
                <title>{`${post.title} - Next Bootstrap`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <NavBarTop />

            <main>
                <div className="container py-5">
                    <div className="row g-4">
                        <div className="col-md-8">
                            <div className="card shadow-blog border-0">
                                <Image
                                    alt="Image"
                                    src={post.image}
                                    width="450"
                                    height="400"
                                    className="card-img-top img-fluid"
                                />
                                <div className="card-body">
                                    <h3 className="card-title">{post.title}</h3>
                                    <div className="d-flex blog-meta py-2">
                                        <Link href="#">
                                            <a className="me-3">
                                                <i className="me-2 icon"><FaUser /></i>
                                                {post.author}
                                            </a>
                                        </Link>
                                        <Link href="#">
                                            <a>
                                                <i className="me-2 icon"><FaRegCalendarAlt /></i>
                                                {post.date}
                                            </a>
                                        </Link>
                                    </div>
                                    <p className="card-text mt-2">{post.body}</p>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-4 px-4">
                            {/* <div className="card shadow-sm">
                                
                            </div> */}
                        </div>
                    </div>
                </div>
            </main>
            
            <Footer />
        </>
    )
}

// This gets called on every request to this page
export async function getServerSideProps({ params }) {
    // console.log(params.slug)
    // Call external API from here directly using slug params
    const getSinglePost = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/post/${params.slug}`);
    const post = await getSinglePost.json();
    // console.log(getSinglePost.status)
    if (getSinglePost.status == 404) {
        return {
            notFound: true,
        }
    } 
    return {
        props: { post },
    }
}