import Head from "next/head";
import NavBarTop from "../components/NavBarTop";
import Footer from "../components/Footer";
import Breadcrumb from "../components/Breadcrumb";
import Gallery from "react-photo-gallery";
import Carousel, { Modal, ModalGateway } from "react-images";
import React, { useState, useCallback } from "react";

const title = "Foto";

export default function Galeri({ photos }) {
    // console.log(photos)

    const [currentImage, setCurrentImage] = useState(0);
    const [viewerIsOpen, setViewerIsOpen] = useState(false);

    const openLightbox = useCallback((event, { photo, index }) => {
        setCurrentImage(index);
        setViewerIsOpen(true);
    }, []);

    const closeLightbox = () => {
        setCurrentImage(0);
        setViewerIsOpen(false);
    };

    const lightboxStyles = {
        header: (base, state) => {
            const opacity= 1;
            const transform = "translateY(10px)"
            return { ...base, opacity, transform};
        },
        navigation: (base, state) => {
            const opacity= 1;
            return { ...base, opacity};
        },
        footer: (base, state) => {
            const opacity= 1;
            const transform = "translateY(-10px)"
            return { ...base, opacity, transform};
        }
    }

    return (
        <>
            <style jsx>
                {`
                main {
                    margin-top: 60px;
                    min-height: 100vh;
                }
            `}
            </style>

            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

            </Head>

            <NavBarTop />

            <main>
                <div className="bg-light">
                    <Breadcrumb pageName="Galeri" currentPage="Foto" />
                </div>

                <div className="container my-5">
                    <Gallery photos={photos} onClick={openLightbox} />
                    <ModalGateway>
                        {viewerIsOpen ? (
                            <Modal onClose={closeLightbox}>
                                <Carousel 
                                    styles={lightboxStyles}
                                    showNavigationOnTouchDevice={true}
                                    currentIndex={currentImage}
                                    views={photos.map(x => ({
                                        ...x,
                                        srcset: x.srcSet,
                                        caption: x.title
                                    }))}
                                />
                            </Modal>
                        ) : null}
                    </ModalGateway>
                </div>

            </main>

            <Footer />

        </>
    );
};

// This gets called on every request to this page
export async function getServerSideProps() {
    const getDataPhotos = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/photo`);
    const photos = await getDataPhotos.json();
    // console.log(photos)
    return {
        props: { photos }, // will be passed to the page component as props
    };
};