import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBarTop from '../components/NavBarTop'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBarTop />

      <main className="mt-5 pt-5">
        <h1>Index Page</h1>
      </main>
      <main className={`mt-5 ${styles.main}`} >
        <h1>Next-Bootstrap</h1>
      </main>

      <footer className={styles.footer}>
      </footer>
    </>
  )
}
