import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import NavBarTop from '../components/NavBarTop'
import Carousel from '../components/Carousel'
import Footer from '../components/Footer'
import { FaArrowRight } from "react-icons/fa"

const title = "Home - Next Bootstrap"

export default function Home({posts}) {

    // Take only 3 post as featured post 
    const featuredPost = posts.slice(0, 3)

    return (
        <>
            <style jsx>
                {`
                main {
                    margin-top: 60px;
                    min-height: 100vh;
                }
                .card-title {
                    font-weight: 500;
                }
                .shadow-blog {
                    box-shadow: 0 4px 16px rgb(0 0 0 / 10%);
                }
                .card-text {
                    color: #495057;
                    font-size: 15px;
                }
            `}
            </style>

            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBarTop />

            <Carousel />

            <main>
                <div className="container my-5">
                    <div className="d-flex align-items-center justify-content-between mb-4">
                        <h3 className="mb-0">Blog</h3>
                        <Link href="/blog">
                            <a className="text-decoration-none">All Blog
                                <i className="ms-2"><FaArrowRight /></i>
                            </a>
                        </Link>
                    </div>
                    <div className="row g-4">
                        {featuredPost.map(post =>
                            <div className="col-sm-6 col-md-6 col-lg-4" key={post.id}>
                                <article className="card shadow-blog border-0 h-100">
                                    <Image
                                        alt="Image"
                                        src={post.image}
                                        width="350"
                                        height="250"
                                        className="card-img-top img-fluid"
                                    />
                                    <div className="card-body">
                                        <h5 className="card-title">{post.title}</h5>
                                        <p className="card-text mt-2">{post.excerpt}</p>
                                        <Link href={`/blog/${post.slug}`}>
                                            <a className="text-decoration-none">Read More
                                            </a>
                                        </Link>
                                    </div>
                                </article>
                            </div>
                        )}
                    </div>
                </div>
            </main>

            <Footer />
        </>
    )
}

// This gets called on every request to this page
export async function getServerSideProps() {
    const getAllPosts = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/post`);
    const posts = await getAllPosts.json()
    return {  
        // will be passed to the page component as props
        props: { posts }, 
    }
}